# Generated by Django 4.1.7 on 2023-05-24 07:53

from django.db import migrations


def fill_index_page_instances(apps, schema_editor):
    Saloon = apps.get_model('beautyapp', 'Saloon')
    Service= apps.get_model('beautyapp', 'Service')
    ServiceGroup = apps.get_model('beautyapp', 'ServiceGroup')

    saloons = [
        {
            'name': 'BeautyCity Московский',
            'address': 'Московский пр., д. 45',
            'city': 'Санкт-Петербург'
        },
        {
            'name': 'BeautyCity Ленинский',
            'address': 'Ленинский пр., д. 45',
            'city': 'Санкт-Петербург'
        },
        {
            'name': 'BeautyCity Литейный',
            'address': 'Литейный пр., д. 45',
            'city': 'Санкт-Петербург'
        },
    ]

    service_groups = [
        {
        'name': 'Парикмахерские услуги',
        'order': 1,
        },
        {
        'name': 'Макияж',
        'order': 2,
        },
        {
        'name': 'Работа с ногтями',
        'order': 3,
        },
    ]

    services = [
        {
            'name': 'Укладка волос',
            'price': 800,
            'order': 2,
            'group': 1,
            'duration': 40,
        },
        {
            'name': 'Вечерний Макияж',
            'price': 1500,
            'order': 1,
            'group': 2,
            'duration': 30,
        },
        {
            'name': 'Окрашивание волос',
            'price': 3200,
            'order': 3,
            'group': 1,
            'duration': 60,
        },
        {
            'name': 'Педикюр',
            'price': 2000,
            'order': 4,
            'group': 3,
            'duration': 60,
        },
        {
            'name': 'Маникюр',
            'price': 2400,
            'order': 4,
            'group': 3,
            'duration': 60,
        },
    ]


    for saloon in saloons:
        Saloon.objects.get_or_create(
            name=saloon['name'],
            address=saloon['address'],
            city=saloon['city']
        )

    for service_group in service_groups:
        ServiceGroup.objects.get_or_create(
            name=service_group['name'],
            order=service_group['order'],
        )

    for service in services:
        Service.objects.get_or_create(
            name=service['name'],
            order=service['order'],
            price=service['price'],
            group=ServiceGroup.objects.get(id=service['group']),
            duration_in_minutes=service['duration'],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_index_page_instances),
    ]


