# Generated by Django 4.1.7 on 2023-05-24 08:49

from django.db import migrations


def fill_masters_and_speciality(apps, schema_editor):
    Master = apps.get_model('beautyapp', 'Master')
    MasterSpeciality = apps.get_model('beautyapp', 'MasterSpeciality')
    Service= apps.get_model('beautyapp', 'Service')

    specialties = [
        {
        'name': 'Мастер Маникюра',
        },
        {
        'name': 'Парикмахер',
        },
        {
        'name': 'Визажист',
        },
    ]

    masters = [
        {
        'first_name': 'Марина',
        'last_name': 'Петрова',
        'review_count': 12,
        'exp_date': '2020-12-03',
        'speciality': 2,
        'services': 2,
        },
        {
        'first_name': 'Инга',
        'last_name': 'Ветрова',
        'review_count': 23,
        'exp_date': '2014-02-10',
        'speciality': 3,
        'services': 1,
        },
        {
        'first_name': 'Aнастасия',
        'last_name': 'Меньшова',
        'review_count': 41,
        'exp_date': '2016-05-11',
        'speciality': 1,
        'services': 3,
        },
    ]

    for speciality in specialties:
        MasterSpeciality.objects.get_or_create(
            name=speciality['name']
        )

    for master in masters:
        master = Master.objects.get_or_create(
            first_name=master['first_name'],
            last_name=master['last_name'],
            review_count=master['review_count'],
            start_experience_date=master['exp_date'],
            speciality=MasterSpeciality.objects.get(id=master['speciality']),
        )

class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0002_auto_20230524_0753'),
    ]

    operations = [
        migrations.RunPython(fill_masters_and_speciality),
    ]
