# Generated by Django 4.1.7 on 2023-05-24 19:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0004_saloon_closing_time_saloon_opening_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время создания отзыва')),
                ('text', models.TextField(verbose_name='текст отзыва')),
                ('raiting', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='оценка от 0 до 5')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notes', to='beautyapp.note')),
            ],
        ),
    ]
