# Generated by Django 4.1.7 on 2023-05-24 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to='beautyapp.note'),
        ),
    ]
