# Generated by Django 4.1.7 on 2023-05-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0006_alter_review_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
    ]
