# Generated by Django 4.1.7 on 2023-05-24 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0007_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='beautyapp.payment'),
        ),
    ]
