# Generated by Django 4.1.7 on 2023-05-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0008_alter_note_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
    ]
